/** Marketing 完整文案（zh / es） */

export const marketingZh = {
  title: "增长计划",
  lead: "Marketing / 增长计划",
  description: "Karuma 生意增长执行手册 · 诊断、目标、拍摄与复盘",
  diagnosisTitle: "Karuma 当前诊断",
  seatsLabel: "座位",
  seatsValue: "50个",
  googleRating: "4.9星",
  googleReviews: "420条评论",
  tiktokFollowers: "63粉丝",
  tiktokLikes: "168赞",
  instagramFollowers: "496粉丝",
  instagramPosts: "30个帖子",
  instagramViews30d: "过去30天 10.8万浏览",
  sundayRevenueLabel: "周日营业额",
  sundayRevenueValue: "2600€",
  pricingLabel: "价格",
  pricingValue: "晚上 / 周末 24.50€\n酒水另算",
  problemLabel: "当前问题",
  problem:
    "产品口碑很好，但知道 Karuma 的人还不够多。周日晚上 21:00 还有很多空桌，说明主要问题是曝光不足和周日晚间转化不足。",
  positioningTitle: "Karuma 核心定位",
  positioningLines: [
    "24,50€ sushi ilimitado + grill en Valencia",
    "4.9⭐ en Google",
    "+420 reseñas",
  ],
  positioningNote: "所有视频、简介、海报、外卖封面都围绕：",
  positioningKeywords: [
    "24,50€",
    "Sushi ilimitado",
    "Grill",
    "Valencia",
    "4.9⭐",
    "+420 reseñas",
  ],
  goalsTitle: "30天目标",
  goalFans: "粉丝",
  goalReviews: "条",
  goalSundayRevenue: "周日营业额",
  googleReviewsGoal: "Google 评论",
  videoPublishTitle: "短视频发布",
  videoPublishItems: [
    "每天 TikTok 3条",
    "每天 Instagram Reels 3条",
    "第一周目标：21条视频",
  ],
  domingoTitle: "Domingo Sushi Night",
  domingoGoalLabel: "目标",
  domingoGoal: "专门拉升周日晚上客流。",
  domingoThemeLabel: "主题文案",
  domingoThemeLines: [
    "¿Domingo sin plan?",
    "Sushi ilimitado + grill por 24,50€",
    "Karuma Sushi & Grill · Valencia",
  ],
  domingoShotsLabel: "拍摄重点",
  domingoShots: [
    "周日晚上氛围",
    "满桌寿司",
    "烤肉",
    "朋友聚餐",
    "甜品",
    "价格展示",
  ],
  domingoRulesLabel: "执行规则",
  domingoRules:
    "每周四、周五、周六、周日都发布 Domingo Sushi Night 相关视频。",
  strategyTitle: "拍摄策略",
  strategyHeadline: "不要拍老板，拍 Karuma",
  strategyIntro: "老板不用出镜。",
  strategyFocusLabel: "重点拍：",
  strategyFocus: [
    "寿司自助餐冲击感",
    "满桌寿司",
    "厨房制作",
    "炙烧三文鱼",
    "烤肉",
    "甜品",
    "客人视角",
  ],
  tomorrowTitle: "明天必须拍的6条视频",
  tomorrowSubtitle: "6 条拍摄清单",
  taskLabel: "任务",
  shotsLabel: "镜头",
  subtitlesLabel: "字幕",
  dailyPlanTitle: "每日发布计划",
  dailyPublish: "每天发布",
  dailyUnit: "条",
  weekOneGoal: "第一周目标",
  weekOneUnit: "条视频",
  scriptsTitle: "视频脚本库",
  scriptLabel: "脚本",
  scriptTitle: "标题",
  scriptHook: "开头3秒",
  scriptOpening: "开头",
  scriptBody: "正文",
  scriptClosing: "结尾",
  bioOptimizeTitle: "账号简介优化",
  tiktokBioCurrentLabel: "TikTok 当前简介",
  tiktokBioCurrent:
    "Buffet libre sushi y carne en Plaza ayuntamiento. Calle roger de lauria 2 46002 valencia.",
  tiktokBioSuggestedLabel: "建议简介",
  tiktokDiagnosisTitle: "TikTok 账号诊断",
  tiktokBioTitle: "TikTok 简介优化建议",
  tiktokBioLines: [
    "🍣 Sushi buffet ilimitado en Valencia",
    "🔥 Sushi, grill y postres",
    "⭐ 4.9 en Google · +420 reseñas",
    "📍Roger de Lauria 2, Valencia",
  ],
  instagramDiagnosisTitle: "Instagram 账号诊断",
  statFollowers: "粉丝",
  statLikes: "获赞",
  statPosts: "帖子",
  statViews30d: "过去30天浏览",
  assetsTitle: "视频素材库",
  assetsSubtitle: "静态展示（mock）",
  assetsNote: "素材管理表暂时以静态模式展示。",
  rulesTitle: "短视频执行规则",
  reviewTitle: "每周复盘",
  reviewWeek: "周期",
  reviewVideos: "发布视频",
  reviewTiktok: "TikTok新增粉丝",
  reviewInstagram: "Instagram新增粉丝",
  reviewGoogle: "Google新增评论",
  reviewSunday: "周日营业额",
  reviewBestVideo: "最好视频",
  reviewWorstVideo: "最差视频",
  reviewNextWeek: "下周改进",
  contentRules: [
    "不要拍老板，拍 Karuma",
    "不拍广告感视频",
    "第一秒必须出现价格、评分或食物冲击",
    "不要第一秒放 Logo",
    "Logo 放最后",
    "视频长度 8-18秒",
    "同一条视频同步发布 TikTok 和 Instagram Reels",
    "前两周不看播放量，只看发布数量",
  ],
  statusNotStarted: "待拍摄",
  statusFilmed: "已拍摄",
  statusPublished: "已发布",
  statusGood: "效果好",
  statusBad: "效果差",
  viralSeriesTitle: "固定爆款系列",
  viralSeries: [
    {
      name: "24.50€挑战",
      examples: [
        "24.50€能吃多少三文鱼？",
        "24.50€能吃多少寿司？",
        "24.50€值不值？",
      ],
    },
    {
      name: "厨房系列",
      examples: [
        "100 piezas en 60 segundos",
        "Cómo hacemos el sushi",
        "Preparando el buffet antes de abrir",
      ],
    },
    {
      name: "客人视角",
      examples: [
        "¿Qué es lo mejor de Karuma?",
        "Encontré un buffet japonés 4.9⭐ en Valencia",
        "¿Cuánto puedes comer por 24,50€?",
      ],
    },
  ],
  bloggerTitle: "Valencia 本地博主合作",
  bloggerTargetsLabel: "目标博主",
  bloggerTargets: "Valencia 本地美食 / 计划 / 餐厅账号",
  bloggerFansLabel: "粉丝范围",
  bloggerFansRange: "5,000 - 30,000",
  bloggerOfferLabel: "合作方式",
  bloggerOffer: "邀请2人免费吃",
  bloggerExchangeLabel: "换取",
  bloggerExchange: ["1条 Reels", "3个 Story"],
  bloggerMustShowLabel: "必须出现",
  bloggerMustShow: [
    "24,50€ sushi ilimitado",
    "4.9⭐ Google",
    "Roger de Lauria 2",
    "Karuma Sushi & Grill",
  ],
  bloggerGoalLabel: "目标",
  bloggerGoal: "每月合作4个本地博主。",
  googleReviewPlanTitle: "Google 评论增长",
  googleReviewCurrentLabel: "当前",
  googleReviewTargetLabel: "目标",
  serverScriptLabel: "服务员结账话术",
  serverScript:
    "Si os ha gustado, ¿nos ayudáis con una reseña en Google? Nos ayuda muchísimo.",
  tableCardLabel: "桌牌文案",
  tableCardText:
    "¿Te ha gustado Karuma?\nDéjanos una reseña en Google 🙏\nNos ayudas muchísimo.",
  googleReviewNote: "不要用折扣换评论。只做自然邀请。",
  viralProductTitle: "流量菜 / Producto viral",
  viralProductSuggestion: "Karuma Sushi Burger\n或\nSushi Tower",
  viralProductPurpose:
    "不是主要靠它赚钱，而是让客人愿意拍视频和分享。",
  viralProductCopyLines: [
    "Solo domingos noche",
    "Karuma Sushi Burger",
    "¿Te atreves?",
  ],
  deliveryTitle: "外卖增长计划",
  deliveryGoal: "用 Uber Eats / Glovo 补充堂食空位问题。",
  deliveryCombosLabel: "建议套餐",
  deliveryCombos: ["Combo Pareja", "Combo Amigos", "Combo Salmón Lover"],
  deliveryPrinciplesLabel: "原则",
  deliveryPrinciples: ["套餐名称简单", "图片清楚", "减少客人选择困难"],
  rhythmTitle: "30天执行节奏",
  rhythmWeeks: [
    { week: "第1周", plan: "每天发3条短视频", sundayTarget: "周日目标：2800€" },
    {
      week: "第2周",
      plan: "继续每天发3条 · 找1个本地博主",
      sundayTarget: "周日目标：3000€",
    },
    {
      week: "第3周",
      plan: "上线 Domingo Sushi Night",
      sundayTarget: "周日目标：3200€",
    },
    {
      week: "第4周",
      plan: "推出一个流量菜，比如 Sushi Burger",
      sundayTarget: "周日目标：3500€",
    },
  ],
  mobileTodayTasks: "今日拍摄计划",
  mobileMustShoot: "6条必须拍的视频",
  mobileNavToday: "今日拍摄",
  mobileNavScripts: "视频脚本",
  mobileNavDomingo: "周日夜计划",
  mobileNavBio: "账号简介",
  mobileNavBlogger: "博主合作",
  mobileNavReview: "每周复盘",
  mobileSectionToday: "今日拍摄",
  mobileSectionGoals: "30天目标",
  mobileSectionDomingo: "Domingo Sushi Night",
  mobileSectionBio: "账号简介建议",
  mobileSectionDiagnosis: "当前诊断",
  mobileSectionRules: "内容规则",
  mobileSectionViral: "爆款系列",
  mobileSectionBlogger: "博主合作",
  mobileSectionGoogle: "Google评论",
  mobileSectionProduct: "流量菜",
  mobileSectionDelivery: "外卖增长",
  mobileSectionReview: "每周复盘",
  mobileConclusionLabel: "结论",
  mobileConclusion:
    "产品口碑很好，但知道 Karuma 的人还不够多。周日晚上空桌多，需加强曝光与周日转化。",
  mobileGoogleShort: "4.9星 / 420条评论",
  mobileTiktokShort: "63粉丝 · 168赞",
  mobileInstagramShort: "496粉丝 · 30帖子",
  mobileInstagramViewsShort: "过去30天 10.8万浏览",
  tomorrowTasks: [
    {
      title: "24,50€ sushi ilimitado en Valencia",
      shots: ["满桌寿司", "炙烧三文鱼", "烤肉", "乌拉卷", "甜品", "店门口"],
      status: "notStarted",
    },
    {
      title: "Buffet japonés 4.9⭐ en Valencia",
      shots: [
        "Google 4.9截图",
        "门头",
        "店内",
        "寿司特写",
        "客人夹菜",
      ],
      status: "notStarted",
    },
    {
      title: "¿Cuánto puedes comer por 24,50€?",
      shots: ["空桌", "第一盘寿司", "第二盘烤肉", "第三盘甜品", "吃完的桌子"],
      status: "notStarted",
    },
    {
      title: "100 piezas de sushi en 60 segundos",
      shots: ["切鱼", "铺饭", "卷寿司", "切卷", "摆盘", "上桌"],
      status: "notStarted",
    },
    {
      title: "Plan de domingo en Valencia",
      subtitles: ["Sushi ilimitado", "Grill", "Postres", "24,50€"],
      shots: [],
      status: "notStarted",
    },
    {
      title: "Dónde cenar con amigos en Valencia",
      shots: ["一桌朋友", "举杯", "满桌食物", "笑", "结尾门头"],
      status: "notStarted",
    },
  ],
  scripts: [
    {
      title: "24,50€ sushi ilimitado en Valencia",
      hook: "¿Sushi ilimitado por 24,50€ en Valencia?",
      body: "En Karuma Sushi & Grill puedes comer sushi, grill, entrantes y postres sin límite.",
      closing: "Guárdalo para tu próxima cena en Valencia.",
    },
    {
      title: "Buffet japonés 4.9⭐ en Valencia",
      opening: "Encontré un buffet japonés con 4.9 estrellas en Google.",
      closing: "Está en Valencia. Se llama Karuma Sushi & Grill.",
    },
    {
      title: "¿Cuánto puedes comer por 24,50€?",
      opening: "Vamos a ver cuánto sushi podemos comer por 24,50€.",
      closing: "¿Cuánto crees que podrías comer tú?",
    },
  ],
  weeklyReview: [
    {
      weekLabel: "第1周",
      videosPublished: 18,
      tiktokNewFans: 47,
      instagramNewFans: 86,
      googleNewReviews: 9,
      sundayRevenue: 2600,
      bestVideo: "24,50€ sushi ilimitado",
      worstVideo: "店内环境空镜",
      nextImprovement: "加强第一秒价格字幕",
    },
    {
      weekLabel: "第0周（基线）",
      videosPublished: 6,
      tiktokNewFans: 12,
      instagramNewFans: 28,
      googleNewReviews: 3,
      sundayRevenue: 2480,
      bestVideo: "—",
      worstVideo: "—",
      nextImprovement: "启动每日3条发布",
    },
  ],
} as const;

export const marketingEs = {
  title: "Marketing",
  lead: "Marketing / Plan de crecimiento",
  description:
    "Manual de ejecución de crecimiento Karuma · diagnóstico, objetivos, rodaje y revisión",
  diagnosisTitle: "Diagnóstico actual Karuma",
  seatsLabel: "Plazas",
  seatsValue: "50",
  googleRating: "4,9 estrellas",
  googleReviews: "420 reseñas",
  tiktokFollowers: "63 seguidores",
  tiktokLikes: "168 me gusta",
  instagramFollowers: "496 seguidores",
  instagramPosts: "30 publicaciones",
  instagramViews30d: "108 k vistas (30 días)",
  sundayRevenueLabel: "Ventas domingo",
  sundayRevenueValue: "2600€",
  pricingLabel: "Precio",
  pricingValue: "Noche / fin de semana 24,50€\nBebidas aparte",
  problemLabel: "Problema actual",
  problem:
    "La reputación del producto es muy buena, pero todavía no suficiente gente conoce Karuma. Los domingos a las 21:00 hay muchas mesas vacías: falta exposición y conversión el domingo por la noche.",
  positioningTitle: "Posicionamiento clave Karuma",
  positioningLines: [
    "24,50€ sushi ilimitado + grill en Valencia",
    "4.9⭐ en Google",
    "+420 reseñas",
  ],
  positioningNote: "Todos los vídeos, bios, carteles y portadas de delivery giran en torno a:",
  positioningKeywords: [
    "24,50€",
    "Sushi ilimitado",
    "Grill",
    "Valencia",
    "4.9⭐",
    "+420 reseñas",
  ],
  goalsTitle: "Objetivos 30 días",
  goalFans: "seguidores",
  goalReviews: "reseñas",
  goalSundayRevenue: "Ventas domingo",
  googleReviewsGoal: "Reseñas Google",
  videoPublishTitle: "Publicación de vídeos cortos",
  videoPublishItems: [
    "3 TikTok al día",
    "3 Instagram Reels al día",
    "Objetivo semana 1: 21 vídeos",
  ],
  domingoTitle: "Domingo Sushi Night",
  domingoGoalLabel: "Objetivo",
  domingoGoal: "Impulsar el tráfico del domingo por la noche.",
  domingoThemeLabel: "Texto temático",
  domingoThemeLines: [
    "¿Domingo sin plan?",
    "Sushi ilimitado + grill por 24,50€",
    "Karuma Sushi & Grill · Valencia",
  ],
  domingoShotsLabel: "Enfoque de rodaje",
  domingoShots: [
    "Ambiente domingo noche",
    "Mesa llena de sushi",
    "Parrilla",
    "Cena con amigos",
    "Postres",
    "Mostrar precio",
  ],
  domingoRulesLabel: "Regla de ejecución",
  domingoRules:
    "Publicar vídeos de Domingo Sushi Night jueves, viernes, sábado y domingo.",
  strategyTitle: "Estrategia de rodaje",
  strategyHeadline: "No grabes al jefe, graba Karuma",
  strategyIntro: "El dueño no debe salir en cámara.",
  strategyFocusLabel: "Enfócate en:",
  strategyFocus: [
    "Impacto visual del buffet de sushi",
    "Mesa llena de sushi",
    "Cocina en acción",
    "Salmón flameado",
    "Parrilla",
    "Postres",
    "Perspectiva del cliente",
  ],
  tomorrowTitle: "6 vídeos obligatorios mañana",
  tomorrowSubtitle: "6 vídeos planificados",
  taskLabel: "Tarea",
  shotsLabel: "Planos",
  subtitlesLabel: "Subtítulos",
  dailyPlanTitle: "Plan de publicación diaria",
  dailyPublish: "Publicar cada día",
  dailyUnit: "vídeos",
  weekOneGoal: "Objetivo semana 1",
  weekOneUnit: "vídeos",
  scriptsTitle: "Guiones de vídeo",
  scriptLabel: "Guion",
  scriptTitle: "Título",
  scriptHook: "Primeros 3 s",
  scriptOpening: "Inicio",
  scriptBody: "Cuerpo",
  scriptClosing: "Cierre",
  bioOptimizeTitle: "Optimización de bios",
  tiktokBioCurrentLabel: "Bio TikTok actual",
  tiktokBioCurrent:
    "Buffet libre sushi y carne en Plaza ayuntamiento. Calle roger de lauria 2 46002 valencia.",
  tiktokBioSuggestedLabel: "Bio sugerida",
  tiktokDiagnosisTitle: "Diagnóstico cuenta TikTok",
  tiktokBioTitle: "Bio TikTok optimizada",
  tiktokBioLines: [
    "🍣 Sushi buffet ilimitado en Valencia",
    "🔥 Sushi, grill y postres",
    "⭐ 4.9 en Google · +420 reseñas",
    "📍Roger de Lauria 2, Valencia",
  ],
  instagramDiagnosisTitle: "Diagnóstico cuenta Instagram",
  statFollowers: "Seguidores",
  statLikes: "Me gusta",
  statPosts: "Publicaciones",
  statViews30d: "Vistas 30 días",
  assetsTitle: "Biblioteca de vídeos",
  assetsSubtitle: "Vista estática (mock)",
  assetsNote: "Gestión de materiales en modo estático.",
  rulesTitle: "Reglas de ejecución de vídeos cortos",
  reviewTitle: "Revisión semanal",
  reviewWeek: "Semana",
  reviewVideos: "Vídeos publicados",
  reviewTiktok: "Nuevos seg. TikTok",
  reviewInstagram: "Nuevos seg. Instagram",
  reviewGoogle: "Nuevas reseñas Google",
  reviewSunday: "Ventas domingo",
  reviewBestVideo: "Mejor vídeo",
  reviewWorstVideo: "Peor vídeo",
  reviewNextWeek: "Mejora próxima semana",
  contentRules: [
    "No grabes al jefe, graba Karuma",
    "No grabes vídeos con estética de anuncio",
    "El primer segundo debe mostrar precio, nota o comida impactante",
    "No pongas el logo en el primer segundo",
    "Logo al final",
    "Duración 8-18 segundos",
    "Publica el mismo vídeo en TikTok e Instagram Reels",
    "Las dos primeras semanas solo cuenta publicaciones, no reproducciones",
  ],
  statusNotStarted: "Pendiente de grabar",
  statusFilmed: "Grabado",
  statusPublished: "Publicado",
  statusGood: "Buen resultado",
  statusBad: "Mal resultado",
  viralSeriesTitle: "Series virales fijas",
  viralSeries: [
    {
      name: "Reto 24,50€",
      examples: [
        "¿Cuánto salmón puedes comer por 24,50€?",
        "¿Cuánto sushi puedes comer por 24,50€?",
        "¿Vale la pena 24,50€?",
      ],
    },
    {
      name: "Serie cocina",
      examples: [
        "100 piezas en 60 segundos",
        "Cómo hacemos el sushi",
        "Preparando el buffet antes de abrir",
      ],
    },
    {
      name: "Perspectiva del cliente",
      examples: [
        "¿Qué es lo mejor de Karuma?",
        "Encontré un buffet japonés 4.9⭐ en Valencia",
        "¿Cuánto puedes comer por 24,50€?",
      ],
    },
  ],
  bloggerTitle: "Colaboración con bloggers locales Valencia",
  bloggerTargetsLabel: "Cuentas objetivo",
  bloggerTargets: "Comida / planes / restaurantes locales en Valencia",
  bloggerFansLabel: "Rango de seguidores",
  bloggerFansRange: "5.000 - 30.000",
  bloggerOfferLabel: "Oferta",
  bloggerOffer: "Invitar a 2 personas a comer gratis",
  bloggerExchangeLabel: "A cambio de",
  bloggerExchange: ["1 Reels", "3 Stories"],
  bloggerMustShowLabel: "Debe aparecer",
  bloggerMustShow: [
    "24,50€ sushi ilimitado",
    "4.9⭐ Google",
    "Roger de Lauria 2",
    "Karuma Sushi & Grill",
  ],
  bloggerGoalLabel: "Objetivo",
  bloggerGoal: "4 colaboraciones locales al mes.",
  googleReviewPlanTitle: "Crecimiento de reseñas Google",
  googleReviewCurrentLabel: "Actual",
  googleReviewTargetLabel: "Objetivo",
  serverScriptLabel: "Guión al pagar (camarero)",
  serverScript:
    "Si os ha gustado, ¿nos ayudáis con una reseña en Google? Nos ayuda muchísimo.",
  tableCardLabel: "Texto cartel mesa",
  tableCardText:
    "¿Te ha gustado Karuma?\nDéjanos una reseña en Google 🙏\nNos ayudas muchísimo.",
  googleReviewNote:
    "No ofrezcas descuentos a cambio de reseñas. Solo invitación natural.",
  viralProductTitle: "Producto viral / Plato estrella",
  viralProductSuggestion: "Karuma Sushi Burger\no\nSushi Tower",
  viralProductPurpose:
    "No es el principal ingreso: que los clientes graben y compartan.",
  viralProductCopyLines: [
    "Solo domingos noche",
    "Karuma Sushi Burger",
    "¿Te atreves?",
  ],
  deliveryTitle: "Plan de crecimiento delivery",
  deliveryGoal:
    "Usar Uber Eats / Glovo para cubrir huecos de comedor.",
  deliveryCombosLabel: "Combos sugeridos",
  deliveryCombos: ["Combo Pareja", "Combo Amigos", "Combo Salmón Lover"],
  deliveryPrinciplesLabel: "Principios",
  deliveryPrinciples: [
    "Nombres de combo simples",
    "Fotos claras",
    "Menos fricción al elegir",
  ],
  rhythmTitle: "Ritmo de ejecución 30 días",
  rhythmWeeks: [
    {
      week: "Semana 1",
      plan: "3 vídeos cortos al día",
      sundayTarget: "Objetivo domingo: 2800€",
    },
    {
      week: "Semana 2",
      plan: "3 vídeos al día · 1 blogger local",
      sundayTarget: "Objetivo domingo: 3000€",
    },
    {
      week: "Semana 3",
      plan: "Lanzar Domingo Sushi Night",
      sundayTarget: "Objetivo domingo: 3200€",
    },
    {
      week: "Semana 4",
      plan: "Lanzar plato viral, ej. Sushi Burger",
      sundayTarget: "Objetivo domingo: 3500€",
    },
  ],
  mobileTodayTasks: "Plan de grabación de hoy",
  mobileMustShoot: "6 vídeos obligatorios",
  mobileNavToday: "Hoy",
  mobileNavScripts: "Guiones",
  mobileNavDomingo: "Domingo Sushi Night",
  mobileNavBio: "TikTok Bio",
  mobileNavBlogger: "Bloggers",
  mobileNavReview: "Revisión",
  mobileSectionToday: "Hoy",
  mobileSectionGoals: "Objetivos 30 días",
  mobileSectionDomingo: "Domingo Sushi Night",
  mobileSectionBio: "Bio sugerida",
  mobileSectionDiagnosis: "Diagnóstico",
  mobileSectionRules: "Reglas de contenido",
  mobileSectionViral: "Series virales",
  mobileSectionBlogger: "Bloggers",
  mobileSectionGoogle: "Reseñas Google",
  mobileSectionProduct: "Producto viral",
  mobileSectionDelivery: "Delivery",
  mobileSectionReview: "Revisión semanal",
  mobileConclusionLabel: "Conclusión",
  mobileConclusion:
    "Buena reputación, poca notoriedad. Mesas vacías el domingo noche: más exposición y conversión.",
  mobileGoogleShort: "4,9★ / 420 reseñas",
  mobileTiktokShort: "63 seg. · 168 me gusta",
  mobileInstagramShort: "496 seg. · 30 publicaciones",
  mobileInstagramViewsShort: "108 k vistas (30 días)",
  tomorrowTasks: [
    {
      title: "24,50€ sushi ilimitado en Valencia",
      shots: [
        "Mesa llena de sushi",
        "Salmón flameado",
        "Parrilla",
        "Uramaki",
        "Postres",
        "Fachada",
      ],
      status: "notStarted",
    },
    {
      title: "Buffet japonés 4.9⭐ en Valencia",
      shots: [
        "Captura Google 4.9",
        "Fachada",
        "Interior",
        "Primer plano sushi",
        "Cliente sirviéndose",
      ],
      status: "notStarted",
    },
    {
      title: "¿Cuánto puedes comer por 24,50€?",
      shots: [
        "Mesa vacía",
        "Primer plato sushi",
        "Segundo plato parrilla",
        "Tercer plato postres",
        "Mesa después de comer",
      ],
      status: "notStarted",
    },
    {
      title: "100 piezas de sushi en 60 segundos",
      shots: [
        "Corte de pescado",
        "Arroz",
        "Enrollado",
        "Corte del rollo",
        "Emplatado",
        "Servicio",
      ],
      status: "notStarted",
    },
    {
      title: "Plan de domingo en Valencia",
      subtitles: ["Sushi ilimitado", "Grill", "Postres", "24,50€"],
      shots: [],
      status: "notStarted",
    },
    {
      title: "Dónde cenar con amigos en Valencia",
      shots: [
        "Mesa de amigos",
        "Brindis",
        "Mesa llena de comida",
        "Risas",
        "Cierre en fachada",
      ],
      status: "notStarted",
    },
  ],
  scripts: [
    {
      title: "24,50€ sushi ilimitado en Valencia",
      hook: "¿Sushi ilimitado por 24,50€ en Valencia?",
      body: "En Karuma Sushi & Grill puedes comer sushi, grill, entrantes y postres sin límite.",
      closing: "Guárdalo para tu próxima cena en Valencia.",
    },
    {
      title: "Buffet japonés 4.9⭐ en Valencia",
      opening: "Encontré un buffet japonés con 4.9 estrellas en Google.",
      closing: "Está en Valencia. Se llama Karuma Sushi & Grill.",
    },
    {
      title: "¿Cuánto puedes comer por 24,50€?",
      opening: "Vamos a ver cuánto sushi podemos comer por 24,50€.",
      closing: "¿Cuánto crees que podrías comer tú?",
    },
  ],
  weeklyReview: [
    {
      weekLabel: "Semana 1",
      videosPublished: 18,
      tiktokNewFans: 47,
      instagramNewFans: 86,
      googleNewReviews: 9,
      sundayRevenue: 2600,
      bestVideo: "24,50€ sushi ilimitado",
      worstVideo: "Plano vacío interior",
      nextImprovement: "Más subtítulo de precio en el primer segundo",
    },
    {
      weekLabel: "Semana 0 (base)",
      videosPublished: 6,
      tiktokNewFans: 12,
      instagramNewFans: 28,
      googleNewReviews: 3,
      sundayRevenue: 2480,
      bestVideo: "—",
      worstVideo: "—",
      nextImprovement: "Empezar 3 publicaciones diarias",
    },
  ],
} as const;
