import type { Locale } from "@/lib/i18n";

const shared = {
  platforms: [
    {
      name: "Uber Eats",
      sales: "150€",
      orders: "6",
      average: "25€",
      rating: "4.7",
      cancelled: "0",
    },
    {
      name: "Glovo",
      sales: "100€",
      orders: "4",
      average: "25€",
      rating: "4.6",
      cancelled: "1",
    },
  ],
  combos: [
    {
      name: "Combo Pareja",
      price: "29.90€ - 34.90€",
      items: ["24 piezas sushi", "2 entrantes", "2 bebidas"],
    },
    {
      name: "Combo Amigos",
      price: "49.90€ - 59.90€",
      items: ["48 piezas sushi", "4 entrantes", "gyoza / pollo / arroz"],
    },
    {
      name: "Salmón Lover",
      price: "24.90€ - 29.90€",
      items: ["Nigiri salmón", "Uramaki salmón", "Tartar salmón", "Salmón flameado"],
    },
  ],
  menuItems: [
    "Combo Pareja",
    "Combo Amigos",
    "Salmón Lover",
    "Uramaki Mix",
    "Entrantes Pack",
    "Bebidas",
  ],
} as const;

const zh = {
  title: "外卖增长计划",
  description: "帮助 Karuma 提升 Uber Eats / Glovo 外卖营业额",
  currentDelivery: "当前外卖",
  target: "目标",
  deliveryShare: "外卖占比",
  todayActions: "今日重点动作",
  todayActionItems: ["更新两个平台主图", "上线 Combo Pareja", "把三个套餐放到菜单最前面"],
  diagnosisTitle: "当前外卖诊断",
  yesterdayRevenue: "昨天总营业额",
  dineIn: "堂食",
  delivery: "外卖",
  conclusion: "堂食表现不错，但外卖占比偏低。",
  opportunity: "外卖不占座位，是提升营业额的重要机会。",
  goalsTitle: "30天外卖目标",
  current: "当前",
  phaseOne: "第1阶段目标",
  phaseTwo: "第2阶段目标",
  perDay: "/天",
  shareGoal: "外卖占比目标",
  platformsTitle: "重点平台",
  todaySales: "今日销售",
  orders: "订单数",
  averageOrder: "平均客单价",
  rating: "评分",
  cancelled: "取消订单",
  mainProblem: "主要问题",
  platformProblems: ["主图与套餐转化需要提升", "取消订单与配送时间需要检查"],
  combosTitle: "建议新增套餐",
  comboDescriptions: ["适合2人", "适合3-4人", "针对三文鱼爱好者"],
  suggestedPrice: "建议售价",
  pending: "待上线",
  checklistTitle: "外卖优化清单",
  checklist: [
    "更新主图",
    "每个套餐有清楚照片",
    "套餐名字简单",
    "减少客人选择困难",
    "做 2 人套餐",
    "做 3-4 人套餐",
    "做三文鱼爆款套餐",
    "菜单前5个商品必须是高转化套餐",
    "每个平台至少设置 1 个主推套餐",
    "检查配送时间",
    "检查差评原因",
    "每周更新一次封面图",
  ],
  menuTitle: "外卖菜单策略",
  menuHeadline: "不要让客人自己搭配",
  menuDescription:
    "外卖用户下单很快。如果选择太复杂，他们会退出。所以要用套餐降低选择难度。",
  menuStructure: "推荐菜单结构",
  dailyTitle: "每日外卖追踪",
  date: "日期",
  yesterday: "昨天",
  uberSales: "Uber Eats销售",
  glovoSales: "Glovo销售",
  totalDelivery: "总外卖",
  notes: "备注",
  dailyNote: "堂食表现好，外卖需要增长",
  weeklyTitle: "每周复盘",
  weeklyFields: [
    "本周外卖总额",
    "Uber Eats总额",
    "Glovo总额",
    "最好卖套餐",
    "最差套餐",
    "平均客单价",
    "差评数量",
    "下周改进",
  ],
  waitingReview: "待每周复盘",
  ...shared,
} as const;

const es = {
  title: "Plan de crecimiento delivery",
  description: "Plan para aumentar las ventas de Uber Eats y Glovo",
  currentDelivery: "Delivery actual",
  target: "Objetivo",
  deliveryShare: "Peso delivery",
  todayActions: "Acciones prioritarias de hoy",
  todayActionItems: [
    "Actualizar la portada en ambas plataformas",
    "Publicar Combo Pareja",
    "Colocar los tres combos al principio del menú",
  ],
  diagnosisTitle: "Diagnóstico delivery actual",
  yesterdayRevenue: "Facturación total de ayer",
  dineIn: "Sala",
  delivery: "Delivery",
  conclusion: "La sala funciona bien, pero el peso del delivery todavía es bajo.",
  opportunity:
    "El delivery no ocupa mesas y es una oportunidad importante para aumentar la facturación.",
  goalsTitle: "Objetivos delivery a 30 días",
  current: "Actual",
  phaseOne: "Objetivo fase 1",
  phaseTwo: "Objetivo fase 2",
  perDay: "/día",
  shareGoal: "Objetivo de peso delivery",
  platformsTitle: "Plataformas prioritarias",
  todaySales: "Ventas hoy",
  orders: "Pedidos",
  averageOrder: "Ticket medio",
  rating: "Valoración",
  cancelled: "Pedidos cancelados",
  mainProblem: "Problema principal",
  platformProblems: [
    "Mejorar conversión de portada y combos",
    "Revisar cancelaciones y tiempo de entrega",
  ],
  combosTitle: "Combos recomendados",
  comboDescriptions: ["Para 2 personas", "Para 3-4 personas", "Para amantes del salmón"],
  suggestedPrice: "Precio recomendado",
  pending: "Pendiente",
  checklistTitle: "Checklist de optimización delivery",
  checklist: [
    "Actualizar la imagen principal",
    "Cada combo debe tener una foto clara",
    "Usar nombres de combos sencillos",
    "Reducir la dificultad de elección",
    "Crear un combo para 2 personas",
    "Crear un combo para 3-4 personas",
    "Crear un combo viral de salmón",
    "Los primeros 5 productos deben ser combos de alta conversión",
    "Configurar al menos 1 combo principal en cada plataforma",
    "Revisar el tiempo de entrega",
    "Revisar las causas de malas reseñas",
    "Actualizar la portada una vez por semana",
  ],
  menuTitle: "Estrategia del menú delivery",
  menuHeadline: "No obligues al cliente a crear su propio pedido",
  menuDescription:
    "El usuario de delivery decide rápido. Si elegir es demasiado complicado, abandona. Los combos reducen la dificultad de elección.",
  menuStructure: "Estructura recomendada",
  dailyTitle: "Seguimiento diario delivery",
  date: "Fecha",
  yesterday: "Ayer",
  uberSales: "Ventas Uber Eats",
  glovoSales: "Ventas Glovo",
  totalDelivery: "Delivery total",
  notes: "Notas",
  dailyNote: "La sala funciona bien; toca hacer crecer delivery",
  weeklyTitle: "Revisión semanal",
  weeklyFields: [
    "Total delivery semanal",
    "Total Uber Eats",
    "Total Glovo",
    "Combo más vendido",
    "Combo menos vendido",
    "Ticket medio",
    "Número de malas reseñas",
    "Mejora para la próxima semana",
  ],
  waitingReview: "Pendiente de revisión semanal",
  ...shared,
} as const;

export type DeliveryGrowthCopy = typeof zh;

export function getDeliveryGrowthCopy(locale: Locale): DeliveryGrowthCopy {
  return (locale === "es" ? es : zh) as DeliveryGrowthCopy;
}
